var message;
message = "Hello World!";
console.log(message);
message = 'Congratulations! Your tweet has won a prize...';
console.log(message);
message = "Today is a great day!";
console.log(message);
message = "Hello " + "World!";
console.log(message); 
message = 'Congratulations' + '! ' + 'Your tweet has won a prize...';
console.log(message); 
